hmrc/agent-services-account-frontend

- conf/application.conf
It was broken when we reverted to the old template
> [FD][APB-1032] Fix appName

- conf/application.conf
other environemnts will be set via environment specific app-configs
> [APB-1124][LS] Fixed exit survey url to be local

- app/uk/gov/hmrc/agentservicesaccount/GuiceModule.scala
- app/uk/gov/hmrc/agentservicesaccount/connectors/DesConnector.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesController.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/agent_services_account.scala.html
- conf/application.conf
- test/uk/gov/hmrc/agentservicesaccount/connectors/DesConnectorSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/stubs/DesStubs.scala
Also added DesConnector to call DES API#4 to retrieve agency name for the ARN
> [APB-1190][JR,AO] Show agency name on the account page.

- app/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesController.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/SignOutController.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/agent_services_account.scala.html
- conf/app.routes
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/SignOutControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/views/ViewsSpec.scala
> [APB-1899][PT]: Remove Token from Session on SignOut

- app/uk/gov/hmrc/agentservicesaccount/config/ExternalUrls.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/agent_services_account.scala.html
- conf/application.conf
- conf/messages
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
> [APB-3276][SM]: Link agent led de auth to AS homepage

- app/uk/gov/hmrc/agentservicesaccount/views/pages/agent_services_account.scala.html
- conf/application.conf
[ASA-1063][GW] remove all feature flags except agentLedDeAuthLink
> ASA-1063 remove feature flags

- app/uk/gov/hmrc/agentservicesaccount/views/pages/asa_dashboard.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/manage_account.scala.html
- conf/messages.cy
- conf/messages.en
- removed full stops inside <a> tags
- updated some links to use the govuk-link style where it was missing
- accessibility fix (aria link)
> APB-5332 [CS] update service names + fixes

- app/uk/gov/hmrc/agentservicesaccount/models/SuspensionDetails.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
to support client insolvency release
> APB-5653 [CS] Revert AGSV in suspension check

- app/uk/gov/hmrc/agentservicesaccount/views/main.scala.html
> APB-5492 [CS] | close js script tags

- app/uk/gov/hmrc/agentservicesaccount/views/pages/help.scala.html
- conf/messages.cy
- conf/messages.en
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
for help and guidance and ASA dashboard
> APB-6256 [CS] remove MTD VAT refs

- app/uk/gov/hmrc/agentservicesaccount/views/components/secondary_nav.scala.html
> APB-6237 [CS] move the Manage account link

- conf/messages.cy
> apb-6460 [CS] add some welsh for gran perms

- app/uk/gov/hmrc/agentservicesaccount/views/components/h2.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/components/h3.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/components/h4.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/components/p.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/help.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/support/Css.scala
- existing content moved to `taxServicesItem` in accordion 
- also small changes to p and heading components
- welsh keys added where missing but with english text
> APB-6459 [CS] update help and guidance (no welsh)

- app/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesController.scala
- app/uk/gov/hmrc/agentservicesaccount/views/components/h1.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/components/h2.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/account_details.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/your_account.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/support/Css.scala
also updates routing for manage account & account details
> [CS] fixes for your-account page

- app/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesController.scala
- app/uk/gov/hmrc/agentservicesaccount/views/main.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/account_details.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/administrators.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/support/Css.scala
- also updated filter to show both "Admin" and "User" types
> [CS] add backlink to administrators page

- app/uk/gov/hmrc/agentservicesaccount/connectors/AgentPermissionsConnector.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesController.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/BetaInviteController.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/asa_dashboard.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/stubs/AgentPermissionsStubs.scala
- note unable to dismiss banner without backend support (WIP)
> APB-6582 [CS] add beta recruitment banner to home

- app/uk/gov/hmrc/agentservicesaccount/config/AppConfig.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/asa_dashboard.scala.html
- conf/application.conf
- test/uk/gov/hmrc/agentservicesaccount/support/BaseISpec.scala
"features.enable-ITSA-Accordion" very old, always true
"features.enable-help-and-guidance" unused
> APB-6592 [CS] Remove ITSA-Accordion & help-and-guidance feature flags

- app/uk/gov/hmrc/agentservicesaccount/connectors/AgentPermissionsConnector.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/BetaInviteController.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/asa_dashboard.scala.html
- conf/app.routes
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
see APB-6582 branch on agent-permissions - will update the button styling to a link later if needed
> APB-6582b [CS] add post req to hide invite

- app/uk/gov/hmrc/agentservicesaccount/controllers/BetaInviteController.scala
- app/uk/gov/hmrc/agentservicesaccount/forms/BetaInviteContactDetailsForm.scala
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/agentservicesaccount/forms/BetaInviteContactDetailsFormSpec.scala
> APB-6589 [CS] add phone regex and some welsh

- app/assets/stylesheets/application.scss
- app/uk/gov/hmrc/agentservicesaccount/config/AppConfig.scala
- app/uk/gov/hmrc/agentservicesaccount/connectors/EmailConnector.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/BetaInviteController.scala
- app/uk/gov/hmrc/agentservicesaccount/models/SendEmailData.scala
- app/uk/gov/hmrc/agentservicesaccount/services/EmailService.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/asa_dashboard.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/beta_invite/check_answers.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/beta_invite/confirmation.scala.html
- conf/application.conf
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/agentservicesaccount/controllers/BetaInviteControllerSpec.scala
- will still need to wait for template merge before QA
- also updates styling of buttons to links for PB invite journey
> APB-6626 [CS] implement sending of email

- app/uk/gov/hmrc/agentservicesaccount/services/EmailService.scala
@Nagavemuri1 merge once you are finished testing the email
> APB-6583 [CS] remove QA from email send list

- app/assets/stylesheets/application.scss
also restores govuk-crest in footer
> APB-6667 [CS] update link styling

- app/uk/gov/hmrc/agentservicesaccount/connectors/AgentPermissionsConnector.scala
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- Handle timeouts when backend takes time building ES3 cache in the background
> Increases request timeout for call to fetch Optin status

- app/uk/gov/hmrc/agentservicesaccount/connectors/AgentPermissionsConnector.scala
- app/uk/gov/hmrc/agentservicesaccount/connectors/AgentUserClientDetailsConnector.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesController.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/ManageLandingController.scala
- app/uk/gov/hmrc/agentservicesaccount/models/AccessGroupSummaries.scala
- app/uk/gov/hmrc/agentservicesaccount/models/ManageAccessPermissionsConfig.scala
- app/uk/gov/hmrc/agentservicesaccount/views/components/summary_list.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/assistant/administrators.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/assistant/your_account.scala.html
- conf/messages
- project/AppDependencies.scala
- test/uk/gov/hmrc/agentservicesaccount/connectors/AgentUserClientDetailsConnectorSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/ManageLandingControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/stubs/AgentPermissionsStubs.scala
- test/uk/gov/hmrc/agentservicesaccount/stubs/AgentUserClientDetailsStubs.scala
+ and updates agent-mtd-identifiers lib
> APB-7091 [CS] update layout/content for 'Your account'

- app/uk/gov/hmrc/agentservicesaccount/auth/AuthActions.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesController.scala
- app/uk/gov/hmrc/agentservicesaccount/views/main.scala.html
- build.sbt
- project/AppDependencies.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/support/LogCapturing.scala
- test/uk/gov/hmrc/agentservicesaccount/support/MetricsTestSupport.scala
+ major version bump for live service status
> live [CS] bump play-frontend-hmrc

- app/uk/gov/hmrc/agentservicesaccount/views/pages/suspend/suspension_warning.scala.html
> APB-6757 Removed feedback page when signed out

- app/uk/gov/hmrc/agentservicesaccount/controllers/SuspendedJourneyController.scala
- app/uk/gov/hmrc/agentservicesaccount/services/EmailService.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/suspend/check_recovery_answers.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/suspend/contact_details.scala.html
- conf/messages
- conf/messages.cy
APB-6759 Add agent name to email service/APB-6758 Add content change
> APB-6759 Add agent name to email service

- conf/application.conf
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
https://github.com/hmrc/agent-permissions-frontend/pull/400 paired with changes here
> [APB-7382][iw/cs] update create group url

- app/uk/gov/hmrc/agentservicesaccount/actions/AuthActions.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesController.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/SuspendedJourneyController.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/suspend/check_recovery_answers.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/suspend/confirmation_received.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/suspend/contact_details.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/suspend/recovery_description.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/suspend/suspension_warning.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/SuspendedJourneyControllerSpec.scala
Removed second Navbar from suspended journey and refactor
> APB 6578 bug nav

- app/uk/gov/hmrc/agentservicesaccount/config/AppConfig.scala
- app/uk/gov/hmrc/agentservicesaccount/connectors/AddressLookupConnector.scala
- app/uk/gov/hmrc/agentservicesaccount/connectors/AgentClientAuthorisationConnector.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/ContactDetailsController.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/package.scala
- app/uk/gov/hmrc/agentservicesaccount/forms/UpdateDetailsForms.scala
- app/uk/gov/hmrc/agentservicesaccount/models/addresslookup/ConfirmedResponseAddress.scala
- app/uk/gov/hmrc/agentservicesaccount/models/addresslookup/ModelV2.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/assistant/your_account.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/manage_account.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/manage_account_partials/contact_details_link.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/updatecontactdetails/change_submitted.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/updatecontactdetails/check_updated_details.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/updatecontactdetails/contact_details.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/updatecontactdetails/update_email.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/updatecontactdetails/update_name.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/updatecontactdetails/update_phone.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/ContactDetailsControllerSpec.scala
(all new features are behind a feature flag)
Not fully functional yet.
* Once new details are collected, the call to submit them does nothing as we don't have the spec for that yet.
* Email verification is not yet implemented
Requesting to merge so testing can begin on the parts in scope in the current sprint.
> Apb 7506 designatory details update

- app/uk/gov/hmrc/agentservicesaccount/views/pages/asa_dashboard.scala.html
- project/plugins.sbt
Standard user 'Your account' screen has 'Manage account' in the body 
This body section is now removed for standard users.
> Standard user 'Your account' screen has 'Manage account' in the body

- app/uk/gov/hmrc/agentservicesaccount/actions/Actions.scala
- app/uk/gov/hmrc/agentservicesaccount/actions/AuthActions.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/AmlsConfirmationController.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/AMLS/update_confirmation_received.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/agentservicesaccount/controllers/AmlsConfirmationControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/BetaInviteControllerSpec.scala
APB-7610 Display AMLS Update Confirmation & test.
Deleted withFullUserDetails/failure handler as it is redundant.
> APB-7610 Display AMLS Update Confirmation & test.

- app/uk/gov/hmrc/agentservicesaccount/controllers/NoAccessGroupsAssignmentController.scala
- conf/app.routes
- test/uk/gov/hmrc/agentservicesaccount/controllers/NoAccessGroupsAssignmentControllerSpec.scala
redirects based off credential role
> APB-7676 [CS] new "no assignment" endpoint

- conf/messages.cy
the wrong single quote character ' that normally escapes things in the messages file was being used instead of ’
> APB-7677 [CS] update welsh ' to ’

- app/uk/gov/hmrc/agentservicesaccount/connectors/AgentAssuranceConnector.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/AMLS/update_money_laundering_supervision_details.scala.html
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/agentservicesaccount/views/pages/AMLS/UpdateMoneyLaunderingSupervisionDetailsViewSpec.scala
> ABP-7547_RW error messages & Tests

- conf/app.routes
- conf/messages
- conf/messages.cy
- test/uk/gov/hmrc/agentservicesaccount/controllers/amls/AmlsConfirmationControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/views/pages/amls/AmlsConfirmationControllerViewSpec.scala
content change and new test view file
> ABP-7801 content change and new test view file

- app/uk/gov/hmrc/agentservicesaccount/views/pages/contact_details/before_you_start_page.scala.html
- conf/messages
- conf/messages.cy
PR has came back after testing in QA
> ABP-7688 QA changes

- app/uk/gov/hmrc/agentservicesaccount/controllers/amls/AmlsNewSupervisoryBodyController.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/amls/new_supervisory_body.scala.html
- test/uk/gov/hmrc/agentservicesaccount/controllers/amls/AmlsNewSupervisoryBodyControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/views/pages/amls/AmlsNewSupervisoryBodyViewSpec.scala
> Supervisory body pre-populated change

- app/uk/gov/hmrc/agentservicesaccount/views/pages/desi_details/change_submitted.scala.html
Navigation menu removed from confirmation page
> [APB-7789_4] Navigation menu removed from confirmation page

- .github/PULL_REQUEST_TEMPLATE
- app/uk/gov/hmrc/agentservicesaccount/views/pages/desi_details/partials/contact_details_cya_partial.scala.html
- test/uk/gov/hmrc/agentservicesaccount/views/pages/desi_details/partials/ContactDetailsCyaSpec.scala
> Apb 8410 - Sax parser exception fix

- app/uk/gov/hmrc/agentservicesaccount/config/AppConfig.scala
- app/uk/gov/hmrc/agentservicesaccount/connectors/AgentServicesAccountConnector.scala
- app/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/util/DesiDetailsJourneySupport.scala
- app/uk/gov/hmrc/agentservicesaccount/models/PendingChangeRequest.scala
- app/uk/gov/hmrc/agentservicesaccount/repository/PendingChangeRequestRepository.scala
- conf/application.conf
- test/uk/gov/hmrc/agentservicesaccount/connectors/AgentAssuranceConnectorSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/connectors/AgentPermissionsConnectorSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/connectors/AgentServicesAccountConnectorSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/connectors/AgentUserClientDetailsConnectorSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/ApplyCTCodeChangesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/ApplySACodeChangesControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/CheckYourAnswersControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/ContactDetailsControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/EmailVerificationEndpointControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/EnterCTCodeControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/EnterSACodeControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/SelectDetailsControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/UpdateEmailAddressControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/UpdateNameControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/UpdateTelephoneControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/ViewContactDetailsControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/controllers/desiDetails/YourDetailsControllerSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/model/PendingChangeRequestSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/repository/PendingChangeRequestRepositorySpec.scala
- test/uk/gov/hmrc/agentservicesaccount/stubs/AgentServicesAccountStubs.scala
- test/uk/gov/hmrc/agentservicesaccount/support/BaseISpec.scala
- test/uk/gov/hmrc/agentservicesaccount/support/UnitSpec.scala
Please also merge app-config PR: https://github.com/hmrc/app-config-production/pull/23129
> APB-8674 Updated database funcs to include backend connector call

- app/uk/gov/hmrc/agentservicesaccount/actions/AuthRedirects.scala
- conf/application.conf
> Pointing auth redirects to our stubs

- project/AppDependencies.scala
- project/plugins.sbt
This PR fixes the [Accessibility Issue](https://build.tax.service.gov.uk/job/Agents/job/agent-services-account-ui-tests/Accessibility_20Assessment_20Report/) by bumping up the play-front-end-hmrc library to version 9.0.0 as that addresses the removal of the accessibility issue.
> APB-8746: Bump up play-frontend-hmrc to v9.0.0

- app/uk/gov/hmrc/agentservicesaccount/models/AgencyDetails.scala
- app/uk/gov/hmrc/agentservicesaccount/models/desiDetails/DesignatoryDetails.scala
- app/uk/gov/hmrc/agentservicesaccount/models/desiDetails/OtherServices.scala
- app/uk/gov/hmrc/agentservicesaccount/models/desiDetails/YourDetails.scala
- app/uk/gov/hmrc/agentservicesaccount/modules/CryptoProviderModule.scala
- app/uk/gov/hmrc/agentservicesaccount/services/SessionCacheService.scala
- app/uk/gov/hmrc/agentservicesaccount/utils/EncryptedStringUtil.scala
- conf/application.conf
- project/AppDependencies.scala
- test/uk/gov/hmrc/agentservicesaccount/model/DesignatoryDetailsSpec.scala
- test/uk/gov/hmrc/agentservicesaccount/model/YourDetailsSpec.scala
> APB-8276 Setting up field encryption and support for unencrypted old data

- app/uk/gov/hmrc/agentservicesaccount/config/AppConfig.scala
- app/uk/gov/hmrc/agentservicesaccount/views/pages/asa_dashboard.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/dashboard_partials/client_authorisations.scala.html
- app/uk/gov/hmrc/agentservicesaccount/views/pages/dashboard_partials/tax_services_accordion.scala.html
- conf/application.conf
- conf/messages
- test/uk/gov/hmrc/agentservicesaccount/controllers/AgentServicesControllerSpec.scala
> APB-9047 feature switch for ACRF
